sudo: required
dist: trusty
language: go
go:
  - 1.8.3
script:
  - export DOCKER_HUB_REPO=openstorage
  - export DOCKER_HUB_STORK_IMAGE=stork
  - export DOCKER_HUB_TAG=`git rev-parse --short HEAD`
  - make
notifications:
  email:
    on_success: always
    on_failure: always
